/**
 * YouTube Metadata Generator API
 * Proxies requests to the Python AI server (py-server)
 */

import { type NextRequest, NextResponse } from "next/server";

// Python server URL (FastAPI running on port 8000)
const PYTHON_API_URL = process.env.PYTHON_API_URL || "http://localhost:8000";

interface MetadataRequest {
  video_topic: string;
  video_description?: string;
  target_audience?: string;
  keywords?: string[];
  structure?: Record<string, unknown>;
  use_ai?: boolean;
}

export async function POST(req: NextRequest) {
  try {
    const body: MetadataRequest = await req.json();
    const { video_topic, video_description, target_audience, keywords, structure, use_ai } = body;

    // video_topic is always required
    if (!video_topic) {
      return NextResponse.json(
        {
          success: false,
          message: "video_topic is required.",
        },
        { status: 422 }
      );
    }

    // Determine which Python endpoint to call
    let pythonEndpoint: string;
    let pythonPayload: Record<string, unknown>;

    if (structure && typeof structure === "object" && Object.keys(structure).length > 0) {
      // Use dynamic generation endpoint
      pythonEndpoint = `${PYTHON_API_URL}/generate/dynamic`;
      pythonPayload = {
        video_topic,
        video_description: video_description || null,
        target_audience: target_audience || "beginners",
        keywords: keywords || [],
        structure,
        use_ai: use_ai !== false, // default to true
      };
    } else if (video_description || target_audience) {
      // Use full metadata generation endpoint
      pythonEndpoint = `${PYTHON_API_URL}/generate/metadata`;
      pythonPayload = {
        video_topic,
        video_description: video_description || null,
        target_audience: target_audience || "beginners",
        keywords: keywords || [],
        use_ai: use_ai !== false,
      };
    } else {
      return NextResponse.json(
        {
          success: false,
          message: "Either provide 'structure' for dynamic generation, or provide video_description and target_audience for full metadata.",
        },
        { status: 422 }
      );
    }

    console.log(`🔗 Calling Python API: ${pythonEndpoint}`);
    console.log(`📦 Payload:`, JSON.stringify(pythonPayload, null, 2));

    // Call the Python FastAPI server
    const pythonResponse = await fetch(pythonEndpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(pythonPayload),
    });

    if (!pythonResponse.ok) {
      const errorText = await pythonResponse.text();
      console.error(`❌ Python API error (${pythonResponse.status}):`, errorText);

      // Try to parse error details
      let errorDetail = "Python server error";
      try {
        const errorJson = JSON.parse(errorText);
        errorDetail = errorJson.detail || errorJson.message || errorText;
      } catch {
        errorDetail = errorText || `HTTP ${pythonResponse.status}`;
      }

      return NextResponse.json(
        {
          success: false,
          message: errorDetail,
        },
        { status: pythonResponse.status }
      );
    }

    const data = await pythonResponse.json();
    console.log(`✅ Python API response received`);
    console.log(`🤖 Generated by: ${data.generated_by}`);

    return NextResponse.json(
      {
        success: true,
        data
      },
      { status: 200 }
    );

  } catch (error: unknown) {
    console.error("❌ Gemini API Error:", error);

    // Check if it's a connection error to the Python server
    const errorMessage = error instanceof Error ? error.message : "Unknown error";

    if (errorMessage.includes("ECONNREFUSED") || errorMessage.includes("fetch failed")) {
      return NextResponse.json(
        {
          success: false,
          message: "Python AI server is not running. Please start it with: cd py-server && ./run.sh",
          error: errorMessage,
        },
        { status: 503 }
      );
    }

    return NextResponse.json(
      {
        success: false,
        message: errorMessage,
      },
      { status: 500 }
    );
  }
}

/**
 * Health check - also checks Python server status
 */
export async function GET() {
  let pythonServerStatus = "unknown";
  let pythonServerDetails: Record<string, unknown> = {};

  try {
    const healthResponse = await fetch(`${PYTHON_API_URL}/health`, {
      method: "GET",
      signal: AbortSignal.timeout(3000), // 3 second timeout
    });

    if (healthResponse.ok) {
      pythonServerDetails = await healthResponse.json();
      pythonServerStatus = "healthy";
    } else {
      pythonServerStatus = "unhealthy";
    }
  } catch (error) {
    pythonServerStatus = "offline";
    pythonServerDetails = {
      error: error instanceof Error ? error.message : "Connection failed",
      hint: "Start the Python server: cd py-server && ./run.sh",
    };
  }

  return NextResponse.json({
    status: pythonServerStatus === "healthy" ? "healthy" : "degraded",
    version: "5.0.0",
    python_server: {
      url: PYTHON_API_URL,
      status: pythonServerStatus,
      ...pythonServerDetails,
    },
    endpoints: {
      "POST /api/gemini": "Generate metadata (proxies to Python server)",
      "GET /api/gemini": "Health check",
    },
    usage: {
      full_metadata: {
        method: "POST",
        body: {
          video_topic: "Your video topic (required)",
          video_description: "Optional description",
          target_audience: "Optional, defaults to 'beginners'",
          keywords: ["optional", "keywords"],
          use_ai: true,
        },
      },
      dynamic: {
        method: "POST",
        body: {
          video_topic: "Your video topic (required)",
          structure: { titles: "", description: "", hashtags: "", tags: "" },
        },
      },
    },
  });
}
